travis: Update PATH adding pyenv directory and remove need for $<RUN_ENV>
Also update scikit-ci-addons to include fix for travis/install_pyenv
addressing the error reported below.

$ git shortlog 0.6.0..0.10.0 --no-merges
Jean-Christophe Fillion-Robin (15):
      anyci/docker: Consistently display result after loading cached images
      anyci/docker: Use "Config.Image" to identify the images between re-load
      docs: Improve "usage" section
      docs: improve formatting of "add-ons" section
      ci_addons/usage: Fix metavar associated with --install" option
      ci_addons: Improve path/execute cmd to support script_name with/without extension
      scikit-ci: Add python to PATH and remove use of $<PYTHON>
      ci: Update from scikit-ci 0.7.0 to 0.11.0
      scikit-ci: Display "sys.version_info" using a python command
      scikit-ci: Display "PATH" environment variable
      scikit-ci: Test version associated with python code directly executed
      scikit-ci: Remove unneeded setting of "PYTHON" env var
      scikit-ci/travis/osx: Set PATH containins python executable
      travis/install_pyenv: Refactor code introducing "_execute_script" function
      travis/install_pyenv: Check if pyenv python executable exists

Error fixed by scikit-build/scikit-ci-addons@92b955f :

Traceback (most recent call last):
  File "../addons/travis/install_pyenv.py", line 108, in <module>
    install(os.environ['PYTHONVERSION'])
  File "../addons/travis/install_pyenv.py", line 82, in install
    if is_pyenv_installed(py_version):
  File "../addons/travis/install_pyenv.py", line 61, in is_pyenv_installed
    script_file.file.write(script + "\n")
TypeError: 'str' does not support the buffer interface